package models

import pq "github.com/lib/pq"

type Proposals struct {
	Id          uint   `gorm:"primarykey" json:"id"`
	ProposalId  int    `json:"proposal_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Status      string `json:"status"`
	Participate string `json:"participate"`
	StartTime   uint   `json:"start_time"`
	EndTime     uint   `json:"end_time"`
}

type ProposalOptions struct {
	Id         uint           `gorm:"primarykey" json:"id"`
	ProposalId int            `json:"proposal_id"`
	Option     pq.StringArray `gorm:"type:text[]" json:"option"`
}

type CreateProposalRequest struct {
	Id          uint           `gorm:"primarykey" json:"id"`
	ProposalId  int            `json:"proposal_id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Status      string         `json:"status"`
	Participate string         `json:"participate"`
	Option      pq.StringArray `gorm:"type:text[]" json:"option" `
	StartTime   uint           `json:"start_time"`
	EndTime     uint           `json:"end_time"`
}

type GetProposalRequest struct {
	Id          uint           `gorm:"primarykey" json:"id"`
	ProposalId  int            `json:"proposal_id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Status      string         `json:"status"`
	Participate string         `json:"participate"`
	Option      pq.StringArray `gorm:"type:text[]" json:"option" `
	StartTime   uint           `json:"start_time"`
	EndTime     uint           `json:"end_time"`
}

// TableName overrides the default tablename generated by GORM
func (GetProposalRequest) TableName() string {
	return "proposals"
}

type UpdateProposalsRequest struct {
	ProposalId  int64          `json:"proposal_id"`
	Status      string         `json:"status"`
	Participate string         `json:"participate"`
	UpdateMask  pq.StringArray `gorm:"type:text[]" json:"update_mask"`
}

// TableName overrides the default tablename generated by GORM
func (UpdateProposalsRequest) TableName() string {
	return "proposals"
}
